#!/usr/bin/env node
'use strict';
// Generates plugin/ (the Claude Code plugin form, served straight from this repository via .claude-plugin/marketplace.json)
// from the single source of truth in adapters/claude-plugin/. Plugin sessions have `review-gate` on PATH (SessionStart hook),
// so `__RG__` becomes the bare command. Run after editing anything under adapters/claude-plugin/; tests/plugin.test.js checks sync.
const fs = require('node:fs'), path = require('node:path');
const root = path.join(__dirname, '..'), src = path.join(root, 'adapters', 'claude-plugin'), out = path.join(root, 'plugin');
const RG = 'review-gate';
const read = f => fs.readFileSync(path.join(src, f), 'utf8');
const stripFrontmatter = s => s.replace(/^---\n[\s\S]*?\n---\n/, '');
const desc = s => (s.match(/^description:\s*(.+)$/m) || [])[1] || '';
function skill(name, description, body) {
  const dir = path.join(out, 'skills', name); fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 'SKILL.md'), `---\nname: ${name}\ndescription: ${description}\n---\n${body.split('__RG__').join(RG)}`);
}
function build() {
  fs.rmSync(out, { recursive: true, force: true });
  const review = read('commands/review.md'), audit = read('commands/review-gate/audit.md'), backfill = read('commands/review-gate/backfill.md');
  skill('review', desc(review) + ' Use when the user asks to review something — the current work, a branch, a PR — in plain words.', stripFrontmatter(review));
  skill('audit', desc(audit) + ' Use when the user asks to check, inspect or audit the project or its tests (e.g. 「프로젝트 점검해줘」).', stripFrontmatter(audit));
  skill('backfill', desc(backfill) + ' Use when the user asks to update, backfill or write tests from the audit (e.g. 「점검 토대로 테스트 업데이트해줘」).', stripFrontmatter(backfill));
  // the session rules that init writes into CLAUDE.md for npm users — plugins cannot inject CLAUDE.md, so they ship as a skill
  const rules = read('CLAUDE-snippet.md').replace(/<!-- review-gate:(start|end) -->\n?/g, '').replace(/\.claude\/commands\/review-gate\/(audit|backfill)\.md/g, 'the review-gate:$1 skill').replace(/\.claude\/commands\/review\.md/g, 'the review-gate:review skill');
  skill('workflow', 'How code changes are made with review-gate installed: tests first (phase test), implementation with the test lock (phase implement), an independent review before finishing, never weakening tests. Use whenever you are about to change code in this repository, and when unsure how to finish a task here.', rules);
  const hooks = {
    hooks: {
      SessionStart: [{ hooks: [{ type: 'command', command: '[ -n "$CLAUDE_ENV_FILE" ] && printf \'export PATH="%s/bin:$PATH"\\nexport REVIEW_GATE_CMD=review-gate\\n\' "$CLAUDE_PLUGIN_ROOT" >> "$CLAUDE_ENV_FILE"; exit 0', timeout: 5 }] }],
      PreToolUse: [{ matcher: 'Edit|Write|MultiEdit|NotebookEdit|Bash', hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/bin/review-gate.js" guard-tests', timeout: 10 }] }],
      Stop: [{ hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/bin/review-gate.js" on-stop', timeout: 600 }] }],
    },
  };
  fs.writeFileSync(path.join(out, 'hooks.json'), JSON.stringify(hooks, null, 2) + '\n');
  fs.writeFileSync(path.join(out, 'README.md'), '# plugin/ — generated by scripts/build-plugin.js from adapters/claude-plugin/. Do not edit by hand.\n');
}
if (require.main === module) { build(); console.log('plugin/ rebuilt'); }
module.exports = { build };
